Repository tumcms/Open-Infra-Platform, pull requests merged in 2020-08, with the labels that each got.

#196 Small corrections to generator
  Core/src/IfcGeometryConverter/IfcPeekStepReader.cpp
  ExpressBindingGenerator/src/Generator/GeneratorOIP.cpp
  ExpressBindingGenerator/src/Meta/Entity.cpp
  ExpressBindingGenerator/src/Meta/Entity.h
  ExpressBindingGenerator/src/Meta/EntityAttribute.h
  ExpressBindingGenerator/src/Meta/Schema.cpp
  ExpressBindingGenerator/src/Meta/Schema.h
  ExpressBindingGenerator/src/Parser/node.h
Labels: refactoring

#206 Removing annoying warnings from the generator. Just a few remain.
  ExpressBindingGenerator/src/General/main.cpp
  ExpressBindingGenerator/src/Generator/Generator.h
  ExpressBindingGenerator/src/Generator/GeneratorEcho.cpp
  ExpressBindingGenerator/src/Generator/GeneratorOIP.cpp
  ExpressBindingGenerator/src/Generator/GeneratorOIP.h
  ExpressBindingGenerator/src/Meta/Entity.h
  ExpressBindingGenerator/src/Meta/Schema.cpp
  ExpressBindingGenerator/src/Meta/Schema.h
  ExpressBindingGenerator/src/Meta/Type.h
  ExpressBindingGenerator/src/Parser/parser.y
Labels: early-binding-generator, refactoring

#188 [REF] GeomUtils.cpp
  Core/src/IfcGeometryConverter/GeomUtils.cpp
Labels: refactoring

#212 Unit test utilities
  CMakeLists.txt
  Core/src/IfcGeometryConverter/IfcImporterImpl.h
  UnitTests/CMakeLists.txt
  UnitTests/Schemas/IFC4X3_RC1/tessellated-item/src/tessellated-item.cpp
  UnitTests/Utilities/CMakeLists.txt
  UnitTests/Utilities/IfcGeometryModelRenderer/CMakeLists.txt
  UnitTests/Utilities/IfcGeometryModelRenderer/src/IfcGeometryModelRenderer.cpp
  UnitTests/Utilities/IfcGeometryModelRenderer/src/IfcGeometryModelRenderer.h
  cmake/CreateUnitTests.cmake
Labels: enhancement

#186 Fix issue 185 with workaround
  cmake/ConfigureDoxygen.cmake
Labels: bug, documentation

#222 Fixed function template specialization.
  Core/src/IfcGeometryConverter/PlacementConverterImpl.cpp
  Core/src/IfcGeometryConverter/PlacementConverterImpl.h
Labels: IFC, good first issue

#220 Extracted class VisualTest
  Core/src/IfcGeometryConverter/IfcImporter.h
  EarlyBinding/src/EXPRESS/EXPRESSOptional.h
  ExpressBindingGenerator/src/Generator/GeneratorOIP.cpp
  ExpressBindingGenerator/src/Meta/EntityAttribute.cpp
  UnitTests/Schemas/IFC4X1/CMakeLists.txt
  UnitTests/Schemas/IFC4X1/tessellated-item/CMakeLists.txt
  UnitTests/Schemas/IFC4X1/tessellated-item/Data/tessellated-item.ifc
  UnitTests/Schemas/IFC4X1/tessellated-item/Data/tessellated-item.png
  UnitTests/Schemas/IFC4X1/tessellated-item/src/tessellated-item.cpp
  UnitTests/Schemas/IFC4X3_RC1/tessellated-item/src/tessellated-item.cpp
  UnitTests/Utilities/IfcGeometryModelRenderer/CMakeLists.txt
  UnitTests/Utilities/IfcGeometryModelRenderer/src/VisualTest.cpp
  UnitTests/Utilities/IfcGeometryModelRenderer/src/VisualTest.h
Labels: enhancement, example-files, refactoring

#218 Split the generated types into a separated library.
  EarlyBinding/CMakeLists.txt
  ExpressBindingGenerator/src/Generator/GeneratorOIP.cpp
  ExpressBindingGenerator/src/Generator/GeneratorOIP.h
Labels: early-binding-generator, enhancement

#223 Update unit test tessellated item
  UnitTests/Schemas/IFC4X1/tessellated-item/Data/tessellated-item_top.png
Labels: example-files
