Repository tumcms/Open-Infra-Platform, pull requests merged in 2021-06, with the labels that each got.

#459 Created a unit test for polygonal-face-tessellation
  Documentation/markdown/SupportedIFCrepresentations.md
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/CMakeLists.txt
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation.ifc
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_back.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_back_left_bottom.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_bottom.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_front.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_front_left_bottom.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_front_right_bottom.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_left.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_right.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_right_bottom_back.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_top.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_top_front_right.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_top_left_back.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_top_left_front.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/Data/polygonal-face-tessellation_top_right_back.png
  UnitTests/Schemas/IFC4X1/polygonal-face-tessellation/src/polygonal-face-tessellation.cpp
Labels: bug, example-files

#460 Refactoring GeometrySettings.h/.cpp and GeomUtils.h/.cpp
  Core/src/IfcGeometryConverter/GeomUtils.cpp
  Core/src/IfcGeometryConverter/GeomUtils.h
  Core/src/IfcGeometryConverter/GeometrySettings.cpp
  Core/src/IfcGeometryConverter/GeometrySettings.h
Labels: documentation, refactoring

#455 [REF] SplineConverter - Surfaces
  Core/src/IfcGeometryConverter/FaceConverter.h
  Core/src/IfcGeometryConverter/SplineConverter.h
  Core/src/IfcGeometryConverter/SplineUtilities.h
  Documentation/markdown/SupportedIFCrepresentations.md
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/CMakeLists.txt
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots.ifc
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_back.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_back_left_bottom.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_bottom.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_front.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_front_left_bottom.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_front_right_bottom.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_left.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_right.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_right_bottom_back.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_top.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_top_front_right.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_top_left_back.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_top_left_front.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/Data/bspline-surface-with-knots_top_right_back.png
  UnitTests/Schemas/IFC4X1/bspline-surface-with-knots/src/bspline-surface-with-knots.cpp
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/CMakeLists.txt
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots.ifc
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_back.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_back_left_bottom.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_bottom.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_front.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_front_left_bottom.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_front_right_bottom.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_left.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_right.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_right_bottom_back.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_top.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_top_front_right.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_top_left_back.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_top_left_front.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/Data/rational-bspline-curve-with-knots_top_right_back.png
  UnitTests/Schemas/IFC4X1/rational-bspline-curve-with-knots/src/rational-bspline-curve-with-knots.cpp
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/CMakeLists.txt
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots.ifc
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_back.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_back_left_bottom.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_bottom.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_front.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_front_left_bottom.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_front_right_bottom.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_left.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_right.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_right_bottom_back.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_top.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_top_front_right.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_top_left_back.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_top_left_front.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/Data/rational-bspline-surface-with-knots_top_right_back.png
  UnitTests/Schemas/IFC4X1/rational-bspline-surface-with-knots/src/rational-bspline-surface-with-knots.cpp
Labels: IFC, refactoring
