Repository tumcms/Open-Infra-Platform, pull requests merged in 2021-11, with the labels that each got.

#479 Ignoring commented lines for OFF Files
  Core/src/OffConverter/OffReader.cpp
  Core/src/OffConverter/OffReader.h
Labels: bug, refactoring

#484 Implement color reader for OFF Files
  Core/src/OffConverter/OffReader.cpp
  Core/src/OffConverter/OffReader.h
  testdata/Off/cube.off
Labels: enhancement, refactoring

#482 [WIP] Implementing IfcClothoid
  Core/src/IfcGeometryConverter/CurveConverter.h
  Core/src/IfcGeometryConverter/GeomUtils.cpp
  Core/src/IfcGeometryConverter/GeomUtils.h
  Core/src/IfcGeometryConverter/GeometrySettings.h
  Core/src/IfcGeometryConverter/RepresentationConverter.h
  Core/src/IfcGeometryConverter/SolidModelConverter.h
  Core/src/IfcGeometryConverter/SpiralUtils.cpp
  Core/src/IfcGeometryConverter/SpiralUtils.h
Labels: enhancement, IFC, refactoring

#387 Rotating model
  CMakeLists.txt
  UserInterface/Data/pause.ico
  UserInterface/Data/play.ico
  UserInterface/ViewPanel/View.cpp
  UserInterface/ViewPanel/View.h
  UserInterface/ViewPanel/Viewport.cpp
  UserInterface/ViewPanel/Viewport.h
Labels: enhancement, quality_of_life
